# Generated by Django 2.0.7 on 2019-07-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Featured',
            field=models.BooleanField(default=True),
        ),
    ]
